version: '3'
services:
  mysql:
    image: mysql:8 # 使用的镜像
    container_name: nblog-mysql # 启动的实例名称
    environment:
      MYSQL_ROOT_PASSWORD: 24hashiMoonYe # root 用户密码
    ports:
      - "3306:3306" # 端口映射
    volumes:
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
    restart: always # 崩溃后自动重启
    networks:
      - kBlognetwork # 指定网络
  redis:
    image: redis:6
    container_name: nblog-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 24hashiMoonYe
    networks:
      - kBlognetwork
    volumes:
      - ./.redis-data:/data # 持久化
networks:
  kBlognetwork:
